#!/bin/bash -e
# Copyright (c) 2024 TurnKey GNU/Linux - https://www.turnkeylinux.org
# 
# This file is part of buildtasks.
# 
# Buildtasks is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.

export DEBIAN_STABLE=bookworm
this_arch=$(dpkg --print-architecture)
export OS_ARCH="$this_arch"

fatal() { echo "FATAL [$(basename "$0")]: $*" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename "$0")]: $*" 1>&2; }
info() { echo "INFO [$(basename "$0")]: $*"; }

usage() {
cat<<EOF
Syntax: $(basename "$0") [ --options ] full-appname
Patch appliance appname-version with appname-version patch, increment
version and repackage as new version ISO, (re)generating tklbam profile.
Updated changelog MUST exist in patch root directory.

Arguments::

    full-appname        - e.g., core-17.0-bullseye-amd64

Options::

    --publish           - publish iso, release files and tklbam profile
                          - implies '--secupdates'
    --secupdates        - run secupdates
    --updates           - install all available updates
                          - implies '--secupdates'
    --local-iso         - validate and patch local iso; iso must exist in
                          BT_ISOS; hash will be downloaded if it doesn't exist
                          - conflicts with '--publish'

Environment::

    BT_DEBUG            - turn on debugging

EOF
exit 1
}

_validate_version() {
    local version="$1"
    local stable_version="^[1-9][0-9]\.[0-9][0-9]?"
    if [[ $version =~ $stable_version$ ]]; then
        info "Valid stable version: $version"
    elif [[ $version =~ $stable_version(alpha|beta|rc)[1-9]$ ]]; then
        warning "Valid pre-release version: $version"
    else
        fatal "Invalid version: $version"
    fi
}

_validate_codename() {
    local codename="$1"
    [[ "$codename" == "$DEBIAN_STABLE" ]] \
        || fatal "Invalid codename: $codename (expected $DEBIAN_STABLE)"
}

_umount() {
    info "Unmounting resources from rootfs."
    umount -l "$rootfs/run" || true
    umount -l "$rootfs/dev" || true
    umount -l "$rootfs/sys" || true
    umount -l "$rootfs/proc" || true
}


_clean_dirs() {
    if ! (mount | grep -q "$(basename "$rootfs")"); then
        rm -rf "${O:?}/${rootfs:?}"
        rm -rf "${O:?}/${cdroot:?}"
    else
        fatal "$rootfs not unmounted."
    fi
}

_clean_isos() {
    local iso=$1
    rm -rf "${O:?}/${iso:?}"
    rm -rf "${O:?}/${iso:?}.hash"
}

_start() {
    info "cleaning relevant assets before build"
    _clean_isos "$new_isofile"
    _clean_dirs
    if [[ -z "$local_iso" ]]; then
        _clean_isos "$isofile"
    else
        warning "--local-iso set"
        if [[ ! -f "${O:?}/$isofile" ]] || [[ ! -f "${O:?}/$isofile.hash" ]]; then
            fatal "iso &/or hash files do not exist in $BT_ISOS"
        fi
    fi
}

_finish() {
    _umount
    if [[ -z "$BT_DEBUG" ]]; then
        info "cleaning up build assets"
        _clean_dirs
    fi
}

unset appver publish sec_updates all_updates local_iso finish
while [[ "$1" != "" ]]; do
    case $1 in
        --help|-h)      usage;;
        --publish)      publish="yes"
                        sec_updates="yes";;
        --secupdates)   sec_updates="yes";;
        --updates)      all_updates="yes"
                        sec_updates="yes";;
        --local-iso)    local_iso="yes";;
        *)              if [[ -n "$appver" ]]; then
                            usage
                        else
                            appver=$1
                        fi;;
    esac
    shift
done

[[ -z "$BT_DEBUG" ]] || set -x
[[ -n "$appver" ]] || usage

info "Parse and validate args, opts and required build variables"
bt_bugfix_path=$(readlink -f "$0")
bt_dir=$(dirname "$bt_bugfix_path")
export BT="$bt_dir"
export BT_CONFIG=$BT/config
# shellcheck source=/dev/null
source "$BT_CONFIG/common.cfg"

parsed_appname_version=$("$BT/bin/parse-appname-version" "$appver")
read -r appname appversion codename arch <<< "$parsed_appname_version"

split_version="$(sed -En "s|^([0-9]+)\.([0-9]+)|\1 \2|p" <<< "$appversion")"
read -r major_v minor_v  <<< "$split_version"
new_appversion="${major_v}.$((minor_v + 1))"

_validate_version "$appversion"
_validate_version "$new_appversion"
_validate_codename "$codename"
[[ "$arch" == "$OS_ARCH" ]] || fatal "Architecture mismatch: $arch != $OS_ARCH"

export BT_VERSION=${appversion}-${codename}-${arch}
export NEW_BT_VERSION="${new_appversion}-${codename}-${arch}"

name=turnkey-${appname}-${BT_VERSION}
new_name=turnkey-${appname}-${NEW_BT_VERSION}
isofile=$name.iso
new_isofile=$new_name.iso
rootfs=$name.rootfs
cdroot=$name.cdroot
old_sec_pkg=turnkey-${appname}-${appversion}
new_sec_pkg=turnkey-${appname}-${new_appversion}
new_changelog=$new_name.changelog
ver_patch=$BT/patches/${appname}-${BT_VERSION}

[[ -n "$BT_ISOS" ]] || fatal "BT_ISO not set"
if [[ "$publish" == "yes" ]]; then
    [[ -n "$BT_PUBLISH_IMGS" ]] || fatal "BT_PUBLISH_IMGS not set"
    [[ -n "$BT_PUBLISH_META" ]] || fatal "BT_PUBLISH_META not set"
    [[ -n "$BT_PUBLISH_PROFILES" ]] || fatal "BT_PUBLISH_PROFILES not set"
    [[ -n "$local_iso" ]] || fatal "--local-iso conflicts with --publish"
else
    warning "--publish was not set"
fi

#trap _cleanup INT TERM EXIT

if [[ ! -d "$ver_patch" ]]; then
    fatal "Patch not found: $ver_patch"
elif [[ ! -f "$ver_patch/changelog" ]]; then
    fatal "New changelog not found in patch directory"
elif ! grep "^$new_sec_pkg " <(head -1 "$ver_patch/changelog"); then
    fatal "Patch changelog has incorrect version (should be $new_sec_pkg)"
fi

O=$BT_ISOS
mkdir -p "$O"
_start

"$BT/bin/iso-download" "$O" "$BT_VERSION" "$appname"
"$BT/bin/iso-verify" "$O" "$BT_VERSION" "$appname"

info "Unpacking iso and setting up as chroot"
cd "$O"
tklpatch-extract-iso "$isofile"

mount --bind --make-rslave /proc "$rootfs/proc"
mount --bind --make-rslave /sys "$rootfs/sys"
mount --bind --make-rslave /dev "$rootfs/dev"
mount --bind --make-rslave /run "$rootfs/run"

info "Updating appliance rootfs and applying patch"
echo "$new_name" > "$rootfs/etc/turnkey_version"
update_release=/tmp/update-release-pkg
mkdir "$update_release/debs"
"$BT/bin/generate-release-deb" "$new_changelog" "$update_release/debs/"
cat > "$update_release/conf" <<EOF
#!/bin/bash -e
export DEBIAN_FRONTEND=noninteractive
apt-get purge -y $old_sec_pkg
apt-get install -y /$new_sec_pkg*.deb
rm -rf /$new_sec_pkg*.deb
EOF
chmod +x "$update_release/conf"
tklpatch-apply "$update_release"
rm -rf "$update_release"

if [[ -n "$all_updates" ]]; then
    tklpatch-apply "$rootfs" "$BT/patches/apt-upgrade"
elif [[ -n "$sec_updates" ]]; then
    turnkey-install-security-updates
fi

info "Cleaning up rootfs and rebuilding new ISO."
tklpatch-apply "$rootfs" "$BT/patches/clean-old-kernels"
"$BT/bin/rootfs-cleanup" "$rootfs"
"$BT/bin/aptconf-tag" "$rootfs" iso
tklpatch-prepare-cdroot "$rootfs" "$cdroot"
TKLPATCH_ISOLABEL=${appname} tklpatch-geniso "$cdroot" "$new_isofile"

if [[ "$publish" == "yes" ]]; then
    info "Preparing release files & publishing."
    "$BT/bin/generate-signature" "$O/$new_isofile"
    "$BT/bin/generate-manifest" "$rootfs" > "$O/$new_name.manifest"
    "$BT/bin/generate-buildenv" iso "$appname" > "$O/$new_name.iso.buildenv"
    if [[ -e "$BT_PROFILES/$appname" ]]; then
        mkdir -p "$O/$new_name.tklbam"
        export PROFILES_CONF=$BT_PROFILES
        "$BT/bin/generate-tklbam-profile" "$O/$new_name.iso" "$O/$new_name.tklbam"
    else
        fatal "tklbam profile not found: $BT_PROFILES/$appname"
    fi
    "$BT/bin/iso-publish" "$BT_ISOS/$new_name.iso"
fi
_finish
